"""all database table

Revision ID: e5e058c2a544
Revises: 
Create Date: 2025-07-07 09:02:14.290952

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'e5e058c2a544'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('contents',
    sa.Column('content_id', sa.Integer(), nullable=False),
    sa.Column('content_username', sa.String(), nullable=True),
    sa.Column('content_user_picture', sa.String(), nullable=True),
    sa.Column('media_type', sa.String(), nullable=False),
    sa.Column('content_description', sa.String(), nullable=True),
    sa.Column('image_title', sa.String(), nullable=False),
    sa.Column('video_title', sa.String(), nullable=False),
    sa.Column('video_url', sa.String(), nullable=True),
    sa.Column('image_url', sa.String(), nullable=True),
    sa.Column('created_at', sa.TIMESTAMP(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('images', sa.ARRAY(sa.JSON()), nullable=True),
    sa.Column('videos', sa.ARRAY(sa.JSON()), nullable=True),
    sa.Column('slider_images', sa.ARRAY(sa.JSON()), nullable=True),
    sa.Column('slider2_images', sa.ARRAY(sa.JSON()), nullable=True),
    sa.Column('slider2_videos', sa.ARRAY(sa.JSON()), nullable=True),
    sa.PrimaryKeyConstraint('content_id')
    )
    op.create_table('users2',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('first_name', sa.String(), nullable=False),
    sa.Column('last_name', sa.String(), nullable=False),
    sa.Column('user_name', sa.String(), nullable=False),
    sa.Column('email', sa.String(), nullable=False),
    sa.Column('password', sa.String(), nullable=False),
    sa.Column('bio', sa.String(), nullable=True),
    sa.Column('profile_picture', sa.String(), nullable=True),
    sa.Column('created_at', sa.TIMESTAMP(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('email')
    )
    op.create_table('comments',
    sa.Column('comment_id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('content_comment_id', sa.Integer(), nullable=False),
    sa.Column('comment', sa.String(), nullable=False),
    sa.Column('published', sa.Boolean(), server_default='True', nullable=False),
    sa.Column('created_at', sa.TIMESTAMP(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['content_comment_id'], ['contents.content_id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['user_id'], ['users2.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('comment_id')
    )
    op.create_table('dislikes',
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('content_dislike_id', sa.Integer(), nullable=False),
    sa.Column('published', sa.Boolean(), server_default='True', nullable=False),
    sa.Column('created_at', sa.TIMESTAMP(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['content_dislike_id'], ['contents.content_id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['user_id'], ['users2.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('user_id', 'content_dislike_id')
    )
    op.create_table('likes',
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('content_like_id', sa.Integer(), nullable=False),
    sa.Column('published', sa.Boolean(), server_default='True', nullable=False),
    sa.Column('created_at', sa.TIMESTAMP(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['content_like_id'], ['contents.content_id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['user_id'], ['users2.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('user_id', 'content_like_id')
    )
    op.create_table('posts2',
    sa.Column('post_id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('post', sa.String(), nullable=False),
    sa.Column('media_type', sa.String(), nullable=False),
    sa.Column('image_uri', sa.String(), nullable=True),
    sa.Column('video_uri', sa.String(), nullable=True),
    sa.Column('published', sa.Boolean(), server_default='True', nullable=False),
    sa.Column('created_at', sa.TIMESTAMP(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users2.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('post_id')
    )
    op.create_table('votes',
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('post_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['post_id'], ['posts2.post_id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['user_id'], ['users2.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('user_id', 'post_id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('votes')
    op.drop_table('posts2')
    op.drop_table('likes')
    op.drop_table('dislikes')
    op.drop_table('comments')
    op.drop_table('users2')
    op.drop_table('contents')
    # ### end Alembic commands ###
